<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RPC150" name="com.objectfrontier.training.java.jdbc.test.AddressServiceTest" tests="8" failures="2" timestamp="31 Oct 2018 09:28:39 GMT" time="0.439" errors="0">
  <testcase name="testUpdate_negative" time="0.016" classname="com.objectfrontier.training.java.jdbc.test.AddressServiceTest"/>
  <testcase name="testUpdate_positive" time="0.016" classname="com.objectfrontier.training.java.jdbc.test.AddressServiceTest">
    <failure type="java.lang.AssertionError" message="ID not found">
      <![CDATA[java.lang.AssertionError: ID not found
	at org.testng.Assert.fail(Assert.java:94)
	at com.objectfrontier.training.java.jdbc.test.AddressServiceTest.testUpdate_positive(AddressServiceTest.java:86)
	at com.objectfrontier.training.java.jdbc.test.AddressServiceTest.testUpdate_positive(AddressServiceTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testUpdate_positive -->
  <testcase name="testRead_positive" time="0.031" classname="com.objectfrontier.training.java.jdbc.test.AddressServiceTest"/>
  <testcase name="testDelete_positive" time="0.016" classname="com.objectfrontier.training.java.jdbc.test.AddressServiceTest">
    <failure type="java.lang.AssertionError" message="No address found in this ID 7">
      <![CDATA[java.lang.AssertionError: No address found in this ID 7
	at org.testng.Assert.fail(Assert.java:94)
	at com.objectfrontier.training.java.jdbc.test.AddressServiceTest.testDelete_positive(AddressServiceTest.java:171)
	at com.objectfrontier.training.java.jdbc.test.AddressServiceTest.testDelete_positive(AddressServiceTest.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testDelete_positive -->
  <testcase name="testCreate_positive" time="0.032" classname="com.objectfrontier.training.java.jdbc.test.AddressServiceTest"/>
  <testcase name="testRead_negative" time="0.015" classname="com.objectfrontier.training.java.jdbc.test.AddressServiceTest"/>
  <testcase name="testCreate_negative" time="0.297" classname="com.objectfrontier.training.java.jdbc.test.AddressServiceTest"/>
  <testcase name="testDelete_negative" time="0.016" classname="com.objectfrontier.training.java.jdbc.test.AddressServiceTest"/>
</testsuite> <!-- com.objectfrontier.training.java.jdbc.test.AddressServiceTest -->
