<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="842" started-at="2018-11-28T08:24:06Z" finished-at="2018-11-28T08:24:07Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="842" started-at="2018-11-28T08:24:06Z" finished-at="2018-11-28T08:24:07Z">
      <class name="com.objectfrontier.training.java.webservices.test.PersonServletTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.objectfrontier.training.java.webservices.test.PersonServletTest@7dc7cbad]" name="init" is-config="true" duration-ms="16" started-at="2018-11-28T13:54:06Z" finished-at="2018-11-28T13:54:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="testCreatePositive(com.objectfrontier.training.java.webservices.pojo.Person, com.objectfrontier.training.java.webservices.pojo.Person)[pri:0, instance:com.objectfrontier.training.java.webservices.test.PersonServletTest@7dc7cbad]" name="testCreatePositive" duration-ms="811" started-at="2018-11-28T13:54:06Z" data-provider="testCreatePositive" finished-at="2018-11-28T13:54:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Person [id=5, firstName=sri, lastName=ram, email=sriram@gmail.com, birthDate=07-11-1995, createdDate=2018-11-28 13:54:06.593, address=Address [street=Taramani, city=Chennai, postalCode=600028], password=Welcome123, is_admin=false]]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Person [id=5, firstName=sri, lastName=ram, email=sriram@gmail.com, birthDate=07-11-1995, createdDate=2018-11-28 13:54:06.593, address=Address [street=Taramani, city=Chennai, postalCode=600028], password=Welcome123, is_admin=false]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Success! expected [5] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Success! expected [5] but found [6]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:284)
	at com.objectfrontier.training.java.webservices.test.PersonServletTest.testCreatePositive(PersonServletTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreatePositive -->
      </class> <!-- com.objectfrontier.training.java.webservices.test.PersonServletTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
